name: DimitriMartens
favicon: null
layout_spectrum: 0.9111186473164707
typography_spectrum: 0.024780245032161474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#0d0c07'
    - '#896c4e'
    - '#bfb97f'
    - '#5b8a9e'
  brandStrength: 0.7851596062537283
  lightness: 0.16705468553118408
  saturation: 0.782461212715134
  rhythmicContrast: 0.8549146333243698
purpose: []
