name: DimitriMartens
favicon: null
layout_spectrum: 0.00903
typography_spectrum: 0.7653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#0d0c07'
    - '#896c4e'
    - '#bfb97f'
    - '#5b8a9e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
